### ISSUE TITLE
Example script

### ISSUE THREAD

**Issue by mbehrle** [openlabs/product-attribute-strict#9]
1. Can you move data from the tryton core module to this module ?

Yes, you can. An example script is provided to migrate the values from Tryton's default attribute system to this one.

-> it would be quite useful to have this example script shipped.

Thanks!

**Comment by sharoonthomas** [comment]
Hi @mbehrle 

The script is now part of the source code.

**Comment by mbehrle** [comment]
- Sharoon Thomas: " Re: [product-attribute-strict] Example script (#9)" (Tue,
  24 Mar 2015 08:08:43 -0700):

> Hi @mbehrle 
> 
> The script is now part of the source code.

Great! Thanks.

## 

```
Mathias Behrle
PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6
```
